#!/bin/sh
git reset --hard # discard local changes
git checkout master # move to master
git pull # get latest repository version
git fetch --tags # get latest tags
git checkout tags/latest_stable # move to latest stable point
